#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : jsonpickle
Version  : 1.4.1
Release  : 6
URL      : https://files.pythonhosted.org/packages/4c/73/8e58db7955e3b2d98935f55ed40fdb7de142e875ee94616afdea196b0bfa/jsonpickle-1.4.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/4c/73/8e58db7955e3b2d98935f55ed40fdb7de142e875ee94616afdea196b0bfa/jsonpickle-1.4.1.tar.gz
Summary  : Python library for serializing any arbitrary object graph into JSON
Group    : Development/Tools
License  : BSD-3-Clause
Requires: jsonpickle-license = %{version}-%{release}
Requires: jsonpickle-python = %{version}-%{release}
Requires: jsonpickle-python3 = %{version}-%{release}
Requires: importlib_metadata
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : setuptools
BuildRequires : setuptools_scm-python
BuildRequires : tox
BuildRequires : virtualenv

%description
.. image:: https://img.shields.io/pypi/v/jsonpickle.svg
:target: `PyPI link`_
.. image:: https://img.shields.io/pypi/pyversions/jsonpickle.svg
:target: `PyPI link`_

%package license
Summary: license components for the jsonpickle package.
Group: Default

%description license
license components for the jsonpickle package.


%package python
Summary: python components for the jsonpickle package.
Group: Default
Requires: jsonpickle-python3 = %{version}-%{release}

%description python
python components for the jsonpickle package.


%package python3
Summary: python3 components for the jsonpickle package.
Group: Default
Requires: python3-core
Provides: pypi(jsonpickle)
Requires: pypi(importlib_metadata)

%description python3
python3 components for the jsonpickle package.


%prep
%setup -q -n jsonpickle-1.4.1
cd %{_builddir}/jsonpickle-1.4.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1588304010
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/jsonpickle
cp %{_builddir}/jsonpickle-1.4.1/LICENSE %{buildroot}/usr/share/package-licenses/jsonpickle/d168b004e2b3920a6a893cae9f6e7923c4e8470e
cp %{_builddir}/jsonpickle-1.4.1/jsonpickleJS/LICENSE %{buildroot}/usr/share/package-licenses/jsonpickle/502b8fa73760ceab2e36965b01ec88535e230a33
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/jsonpickle/502b8fa73760ceab2e36965b01ec88535e230a33
/usr/share/package-licenses/jsonpickle/d168b004e2b3920a6a893cae9f6e7923c4e8470e

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
